[GAME]
RESOLUTION_SCALE = 2
SCREEN_SIZE_X = 600
SCREEN_SIZE_Y = 400
GRID_SIZE_X = 60
GRID_SIZE_Y = 40
SNAKE_SIZE = 10
BLOCK_SIZE = 10
SNAKE_BODY_SEGMENTS_PER_BLOCK = 16
TICKS_PER_SECOND = 60
FULLSCREEN = false


[PLAYER]
NUMBER_OF_PLAYERS = 1
INITIAL_FOOD = 1
INITIAL_SNAKE_LENGTH = 15
INITIAL_LIVES = 2
SNAKE_SPEED = 4
DEATH_PUNISHMENT = 5

[POWERUPS]
SPEED_POWERUPS = true
GHOST_POWERUPS = true
SHIELD_POWERUPS = true
N_SPEED_POWERUPS = 5
N_GHOST_POWERUPS = 1
N_SHIELD_POWERUPS = 3

[MODE]
TAIL_BITING = true
TAIL_STEALING = false

[GAMEPLAY]
VERZET = false
FREEZE_FRAMES_ON_BITTEN = 300
START_COUNTDOWN = 0
GAME_TIMER_SWITCH = false
GAME_TIMER = 30

[COSMETIC]
BACKGROUND_VISUALS = true
WAVE_RATE = 1.0
MAX_COLOR_SCALE = 3
NEIGHBOURHOOD_SHAPE = 0
AGENT_EFFECT_STEP_SIZE = 5
FREEZE_FRAMES_ON_EAT = 2
PLAYER_SCORE_BOXES = true
BODY_DECAY_RATE = 15

[CONTROLLER]
ENABLE_CONTOLLERS = true
CONTROLLER_DEADZONE = 0.45

[MUSIC]
DISABLE_MUSIC = true
MUSIC_VOLUME = 1.0

[SOUND]
DISABLE_EFFECT_SOUNDS = false
EFFECT_VOLUME = 0.5
MASTER_VOLUME = 1.0

[DEV]
DRAW_COORDINATES = false

